sudo: required
services:
  - docker

env:
  - NODE_VERSION=8-jessie
  - NODE_VERSION=10.8-jessie

script:
  - docker login -u="$NPM_USERNAME" -p="$NPM_PWD"
  - docker build -t node:NODE_VERSION --build-arg NODE_IMAGE=node:${NODE_VERSION}" .
  - docker images
  - docker tag node:$NODE_VERSION $NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push node:$NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)

stages:
  - test
  - npm_targets

jobs:
  - stage: npm_targets
    name: "Test 8-jessie"
    install: skip
    sript:
    -docker run --rm $NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
    env:
      - NODE_VERSION = 8-jessie
      - NODE_TARGET = test
  - stage: npm_targets
    name: "Test 8-jessie"
    install: skip
    sript:
    -docker run --rm $NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
    env:
      - NODE_VERSION = 8-jessie
      - NODE_TARGET = lint
  - stage: npm_targets
    name: "Test 8-jessie"
    install: skip
    sript:
    -docker run --rm $NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
    env:
      - NODE_VERSION = 8-jessie
      - NODE_TARGET = coverage
    - stage: npm_targets
      name: "Test 8-jessie"
      install: skip
      sript:
      -docker run --rm $NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
      env:
        - NODE_VERSION = 10.8-jessie
        - NODE_TARGET = test
    - stage: npm_targets
      name: "Test 8-jessie"
      install: skip
      sript:
      -docker run --rm $NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
      env:
        - NODE_VERSION = 10.8-jessie
        - NODE_TARGET = lint
    - stage: npm_targets
      name: "Test 8-jessie"
      install: skip
      sript:
      -docker run --rm $NPM_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
      env:
        - NODE_VERSION = 10.8-jessie
        - NODE_TARGET = coverage
